add = (a, b) => { return a + b };

subtract = (a, b) => { return a - b };

multiply = (a, b) => {return a * b };

divide = (a, b) => {return a / b };


//calls the above math functions and applies them to a and b
operate = (operator, a, b) => {
    operator(a, b)
 }
//stores the value generated by number buttons
let displayValue = 0;


// populates result container with value taken from "displayValue" variable
function displayNums(displayValue) {
   const results = document.querySelector('.result');
   const text = document.createTextNode(displayValue);
   results.appendChild(text);
   
}

addListenEvent = () => document./////







